- CHANGELOG.md
> Add note about adhering to SemVer

- CHANGELOG.md
was pointing to a different repo
> fix `unreleased` link

- README.md
- index.html
Just ran into the wonders of GitHub for Windows. Hope you don't mind I've created a new request.
See #42
> Update year to match in every example

- README.md
Where supported I updated a few links from http to https
1 link at at time we'll get to HTTPS everywhere.....
> Updated links to https

- source/es-ES/index.haml
I would like to contribute adding the spanish translation ;)
> First version of the spanish translation

- source/de/index.haml
Found some more wrong quotes, little glitches and generally made some phrases sound more natural.
> Improved the German translation

- source/fr/0.3.0/index.html.haml
Hi,
This PR add the French translation.
EDIT: @olivierlacan, it's not WIP anymore, so if somebody wants to review/merge it, I'm fine with it, but at least one review would be great as I think it's far from being perfect.
(From your public location I guess it could be you ;) )
> Add French translation

- source/pt-BR/0.3.0/index.html.haml
Correcting Brazillian Portuguese typos and adding missing parts presents in the original english text.
> Update index.html.haml to correct typos and add missing paragraphs

- CHANGELOG.md
Sorry for this tiny PR @olivierlacan, but after I had submitted the new heading I realized it included an extra whitespace. It drives me crazy every time I copy/paste, so I figured I'll just send a quick PR. Thanks again ❤️!
> Remove extra whitespace

- source/de/0.3.0/index.html.haml
This change does not break backwards compatibility ;-)
I mostly capitalized "Du" and cognates.
Also tried to get closer to the English original in some places.
The translation of the "Why should I care?" section is still quite bad, but I don't know how to do better.
> slight phrasing and spelling changes

- source/cs/0.3.0/index.html.haml
Rough version. Might need refining.
> Czech translation

- source/pl-PL/0.3.0/index.html.haml
First version of Polish translation.
I will update it as soon as English 0.4.0 is published.
> Polish translation

- source/pl-PL/0.3.0/index.html.haml
Fixed a typo and refactored interpunction.
> Typos and interpunction

- source/fr/1.0.0/index.html.haml
Hi,
I fixed a few things in the French translation.
> Fix French translation

- source/es-ES/1.0.0/index.html.haml
Added spanish translation for 1.0.0 version. #164
> Added es-ES for 1.0.0 version

- source/zh-CN/1.0.0/index.html.haml
Simplified Chinese Translation for 1.0.0
> Gg0305 version1.0.0 zh cn

- config.rb
- source/layouts/layout.html.haml
Hi!
I made some changes to fix the language selector according on what was said in #180. Also I did, in a separate commit, a little improvement (from my point of view) in how the selector is built.
> Fix language selector to make it work properly in Firefox

- config.rb
- source/id-ID/1.0.0/index.html.haml
Added Indonesian translation to make it easier to understand for Indonesian developers, I will ask for another native speaker to help me validating this request.
> add indonesian translation

- source/en/1.0.0/index.html.haml
> trivial: "of each version" not "of each versions"

- source/pt-BR/1.0.0/index.html.haml
> Typo Brazilian Portuguese

- source/en/1.0.0/index.html.haml
Fixes https://github.com/olivierlacan/keep-a-changelog/issues/222
> Fix typo - Add missing comma

- source/pl/0.3.0/index.html.haml
- source/pl/1.0.0/index.html.haml
Added translation partially basing on v0.3.0 translation by @amielucha, simplified locale name.
> Add pl v1.0.0 translation, rename pl-PL to pl

- Gemfile.lock
- config.rb
- source/ko/1.0.0/index.html.haml
Hello, I'm Hyounggap An from south Korea.
I found this site exactly when I was struggling with how to keep track of our project changes.
I hope this helps other Korean developers keeping their <code>changelogs.md</code> neat!
Great work!
> Korean translation

- README.md
While you have a greate Development section, it doesnt explicitely state anywhere that contributions are welcome. I have changed that with this redundant text.
> Made contribution explicit

- source/id-ID/1.0.0/index.html.haml
Some updates to the translation so that it is easier to read. Also fixed the link to submit issues.
> Translation update

- source/nl/1.0.0/index.html.haml
> Small updates to the dutch language

- source/en/1.1.0/index.html.haml
Having an inconsistent changelog is bad. I feel this should be mentioned.
> Added bad changelog paragraph on inconsistency

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
> Format all the markdown files with markdownlint

- CHANGELOG.md
Correct link to version 1.1.0 in CHANGELOG.md file.
> Correct link to version 1.1.0

- source/pt-BR/1.0.0/index.html.haml
Updated the Unreleased to the pattern (English Term/Portuguese Term);
> Updated to the pattern en/pt-BR

- source/id-ID/1.0.0/index.html.haml
Hope i can help even if just small fixing things.
> Fixing some indonesian translation and typos

- CHANGELOG.md
- config.rb
- source/da/1.1.0/index.html.haml
> Add Danish (da) translations.

- source/es-ES/1.0.0/index.html.haml
**Before:**
>se han realizados
**After:**
>se han realizado
> Fix small typo in the Spanish answer for the 2nd question

- source/nb/1.1.0/index.html.haml
Adds `nb`, the majority Norwegian written language.
> Add Norwegian Bokmål for version 1.1.0

- source/zh-CN/1.0.0/index.html.haml
> Modify expression.
> Delete space caused by LF.
> Add missed punctuation.
Hi👋@lindexi. Could you please help to review this Pull Request and provide some useful information? Thanks a lot.
> Modify zh-CN

- source/zh-TW/1.0.0/index.html.haml
Hello,
I just wanna modify the wording after browsing the traditional Chinese website of `keep-a-changelog`.
> Modify the zh-TW wording

- data/links.json
1. Fixed isodate link to a correct link
> Fixed isodate link

- CHANGELOG.md
- source/it-IT/1.1.0/index.html.haml
This adds the paragraph `#inconsistent-changes` to update the Italian translation to version 1.1.0.
> Add Italian translation for version 1.1.0

- source/sl/1.0.0/index.html.haml
- source/sl/1.1.0/index.html.haml
This adds Slovenian (sl_SI) translation for the 1.0.0 and 1.1.0 versions.
> Add Slovenian translation for 1.0.0 and 1.1.0

- source/it-IT/1.1.0/index.html.haml
Minor improvements to the Italian translation.
> Fixed Italian translation version 1.1.0

- config.rb
Adding the Norwegian translation page to the menu.
> Add nb transaltion to nav menu

- source/zh-CN/1.1.0/index.html.haml
- source/zh-TW/1.1.0/index.html.haml
Add Traditional Chinese Translation for V1.1.0 and modify Simplified Chinese Translation links issue for V1.1.0
> Add zh-TW v1.1.0 and modify zh-CN v1.1.0 links issue

- CHANGELOG.md
- source/de/1.1.0/index.html.haml
I tried to come up with an accurate German translation of the original English document, as suggested in the contribution section. I tried to stay as close to the original text as possible, adding a passage in the date format section and exchanging a few individual words that felt like they could be put a little differently to match the original English passage better. 
This is my first pull request, so please guide me with feedback if I am doing something wrong.
> German translation for v1.1

- config.rb
- source/ro/1.1.0/index.html.haml
Hello,
I have translated the website into the Romanian language.
It's awesome that exists such a website. Thank you for this kind of learning documentation! 🙌🏼
P.S: Please add the label hacktoberfest-accepted to this PR if you consider 🙏🏻
Cheers 🍻,
Vlad
> Romanian 🇷🇴 language added for the website

- source/cs/1.1.0/index.html.haml
Hello, I did prepare cs translation for version 1.1.0 plus I fixed one typo in the previous cs translation.
> Czech translation 1.1.0

- source/sv/1.1.0/index.html.haml
A few minor changes to the Swedish 1.1.0-translation I came to think of as I read through 1.1
@magol @Ainali please have a look if you happen too find a few minutes.
> Minor update of Swedish 1.1.0

- source/ko/1.1.0/index.html.haml
Hi, My name is Jaewon Yun and my native language is Korean, currently living in South Korea.
I found out about this repository through another open source and since there was no translation of the latest version, I decided to translate it myself.
I naturally fixed the awkward parts of the old 1.0.0 translation and translated the paragraphs added in the 1.1.0 version.
> Add translation for 1.1.0

- source/zh-TW/1.1.0/index.html.haml
- Corrected the Traditional Chinese character from「麵」to「面」to fix a typo.
> fix: corrected Traditional Chinese character error
