- CHANGELOG.md
- README.md
- index.html
To provide more info on the date format, and make it blatantly obvious that the YYYY-MM-DD format is a _standard_, provide a link to the ISO8601 reference page.
> Add ISO date note, and link

- README.md
“That seems like a pipe dream” is not an argument. A lot of things “seem like a pipe dream” to someone or other. That doesn’t mean they cannot be done, nor, more importantly, is it any sort of reason, in and of itself, that they *oughtn’t*.
But there *is* a strong case that can be be made against commit logs as change logs. The section just fails to make it.
This patch adds that.
(I don’t do much with Ruby so I don’t have a meaningful Ruby installation on this machine, and I couldn’t be bothered to set up the toolchain to do the regeneration stuff. So I’m afraid you’ll have to amend the commit before you merge it. Sorry about that.)
> Give some reasoning against using commit logs

- CHANGELOG.md
I don't understand why the linkage `[Unreleased][unreleased]` is necessary. This change keeps it imho simpler.
> Shorter linkage to Unreleased link

- .editorconfig
There are several translations in `source/` directory, so I think this config makes things a bit better!
> Add charset config to .editorconfig

- CHANGELOG.md
Usually every time I'm adding entries to the changelog, I forget the format. I then open the browser and come back to the website to refresh my memory. This is fine, but contributors to the project might not know that the `CHANGELOG.md` follows a specific format, and add headings with different, non-conforming names.
Making it clear what the format is for the CHANGELOG should help level set any contributors.
I ❤️ this project so much! We use this format extensively.
> Add link back to keepachangelog.com

- source/sl/0.3.0/index.html.haml
Hello,
this patch adds a new translation - Slovenian (`sl_SI`). The translation has been double checked and follows Slovenian grammar rules.
In case there is required a second translator to check it out, I can check...
Thank you for considering merging it in the repository as well.
> Slovenian - sl_SI translation for 0.3.0

- CHANGELOG.md
You can only comply with a specification if you know it. Since new versions are released without users knowing it immediately the only valid option is to pin the specification version which you know you comply with.
Ref: https://github.com/olivierlacan/keep-a-changelog/issues/103
Used by: https://github.com/debops/
> Pin format spec major versions

- source/es-ES/1.0.0/index.html.haml
Hi everyone!
I am making this PR in order to improve a little the Spanish translation. I would like to have the feedback of @ZeliosAriex and @leocabeza (who made current Spanish translations) apart from someone else that wants to help.
I also want to discuss about some specific words and achieve an agreement about which could be the best translation for them
* **curated**; in the context of  _a file which contains a curated, chronologically ordered list_ I believe that `saneada` or `limpia`  is the meaning of this word. However, I am not sure about if we should include this translation in the sentence. Probably _un fichero que contiene una lista conológicamente ordeanda_ could be enough.
* **deprecations**; this is a difficult word to translate.  I have no problem to keep it as it in the …
> Improve Spanish translation

- source/assets/stylesheets/application.css.sass
- source/assets/stylesheets/layout.sass
- source/assets/stylesheets/sections.sass
This makes the website more readable on mobile devices. The website design remains identical on desktops/laptops.
The mobile breakpoint applies to all viewports whose width is lower than 1077 pixels (this value was picked so that horizontal scrollbars never appear due to the "extruding" bars on the desktop version).
**Some previews:**
> Make the website use responsive design

- source/nl/1.0.0/index.html.haml
Hi there... 
Even after being a programmer for over 20 years, this is my first pull request. So I hope I'm doing it right. Here is a Dutch translation of your keep a changelog site. @vanhooferwin can help out doing an extra check if you want to have an other native dutch programer to review it.
> Dutch translation of 1.0.0

- CHANGELOG.md
This seemed like to logical place to link the initial release in a CHANGELOG
> Link the initial release

- source/assets/stylesheets/sections.sass
Aligned the `⌄` and `-` in the FAQ (it was mildly annoying me)
Before:
After:
> Center the `⌄` and `-` in the FAQ

- CHANGELOG.md
MD022: Headings should be surrounded by blank lines.
All headings must have a blank line both before and after.
> Headings should be surrounded by blank lines

- CHANGELOG.md
Replace `Portugese` with `Portuguese`.
> Fix typo in language name

- source/layouts/layout.html.haml
See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Contentinfo_role
Note: https://tylerfortune.me/ Is not available anymore (but the dummy page uses https as well)
> Improve footer

- CHANGELOG.md
According to markdown lint (https://dlaa.me/markdownlint/) there are several linting issues with the Changelog:
Line 15 - MD039 Spaces inside link text [Context: "[@tatocaster ]"]
Line 18 - MD022 Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### Changed"]
Line 19 - MD032 Lists should be surrounded by blank lines [Context: "- Fixed typos in Italian trans..."]
> Fix markdown validation issues in CHANGELOG.md

- source/id-ID/1.0.0/index.html.haml
This PR fix typo in indonesian translation.
* Word from `Dhilangkan` to `Dihilangkan`
*  Remove unnecessary english paragraph that already translated.
`Tujuan utama dari commit adalah untuk mencatat setiap perubahan dari source code. Beberapa proyek merapikan commitnya, beberapa tidak.` is the translation of `The purpose of a commit is to document a step in the evolution of the source code. Some projects clean up commits, some don't.`
> Fix typo in id-ID translation

- data/links.json
I noticed that the links to GitHub were linking to '#'. I've fixed the renamed link that was added to `data/links.json`.
> Fixed links to GitHub repo

- CHANGELOG.md
Using periods consistently was discussed in #450 and fixed previously in #451, but some changes have been made since then that did not include a period at the end of the change.
> Add missing periods

- source/id/1.1.0/index.html.haml
I'd like to help the project by translating the latest version into Indonesian, my native language. This project represents a part of software development that I slowly begin to realize the importance of and is a convention I hope I can recommend to my fellow developers soon.
> 1.1.0 id translation

- source/zh-TW/1.1.0/index.html.haml
"高質量" is used mostly in zh-CN, which means "high quality". While in zh-TW it should be "高品質". This PR rectifies this.
> Fix a term for zh-TW
